### ISSUE TITLE
Consider changing Z<Datatype> naming

### ISSUE THREAD

**Issue by FunFunFine** [zio/zio-prelude#825]
Hi!
Currently, `zio-prelude` has some data types that have `Z` prefix in their names along a special properties (e.g. warnings in `ZValidation`). It's understendable that their names must be different in some way to tell them apart from non-`Z`-versions. But this way of adding `Z`-prefix doesn't make it any easier to tell why a data type is special. It also does not correlate with main `zio` library, where `Z` stands for something effect-related (it's not stated anywhere but it feels this way).

IMO it raises cognitive load for  users of `zio-prelude` (especially newcomers), so I propose to change the names somehow (or to add aliases). 
Here is some options that come to my mind:
- `ZValidation -> LogValidation` (or LValidation)
- `ZPure -> Computation` 
- `ZSet -> СalcSet`

WDYT?

**Comment by adamgfraser** [comment]
@FunFunFine Hi! Thanks for the feedback!

The `Z` prefix actually indicates a more polymorphic version of another data type, not a data type that is effectual. So for example `IO` and `ZIO` are equally effectual but `ZIO` is more polymorphic because it has the additional type parameter `R`. Similarly `Ref` and `ZRef` are equally effectual but `ZRef` allows the get and set types to be different and to potentially fail with different errors, and so on for other data types such as `ZQueue` and `ZHub`.

There are also some cases where the `Z` prefix is used to disambiguate a term that might otherwise be too common and create risk of name conflicts (e.g. `ZPool`).

In this context, I think the names of these data types are actually extremely idiomatic. `ZValidation` is a more general version of `Validation` that is polymorphic in the log type. `ZSet` is a more polymorphic version of a `Set` that is polymorphic in the measure type. `ZPure` is more polymorphic than its type aliases in several ways as represented by its different type parameters and also serves to disambiguate it as `Pure` or `Computation` might otherwise be too general.

It is true that these names could individually be more specific in describing in what way these data types are more polymorphic, but I think that would come at the expense of longer names, especially for data types that are polymorphic in multiple ways, and less consistency between these various data types. I also think this convention has also worked very well for the ZIO ecosystem overall.

So I would be inclined to not change these names. The one that I think we could think about is renaming `ZPure` to something like `ZCompute`. We discussed that when `ZPure` was originally developed and could certainly change if we felt like that was a significantly better name, though I am not convinced of that at this point.

**Comment by FunFunFine** [comment]
Well, I see the intention now, thank you! 

I guess I won't be the first who gets such a question, so probably this whole `Z is for More Polymorphic` thing is worth mentioning somewhere on the microsite (perhaps even in ZIO one).

**Comment by adamgfraser** [comment]
Great idea! Copying @khajavi.

**Comment by khajavi** [comment]
Will do!
